export {default as Navbar} from './Navbar'
export {default as Header} from './Header'
export {default as About} from './About'
export {default as Services} from './Services'
export {default as FAQ} from './FAQ'
export {default as Footer} from './Footer'